#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include "ships.h"
#include "battle.h"

void ShowInstructions(){
    int choice;

    printf("\n=== VIEW INSTRUCTIONS ===\n");
    printf("This program simulates a naval battle between a Battleship B and Escort ships E.\n\n");

    printf("1. Start Simulation\n");
    printf("   - Enter battlefield size and number of escort ships.\n");
    printf("   - Enter Battleship type, position and shell velocity.\n");
    printf("   - Escort ship properties and positions are generated by the program.\n\n");

    printf("2. Battle Simulation\n");
    printf("   - Part 1 simulates basic attacks, Battleship movement and gun jamming.\n");
    printf("   - Part 2-A adds a firing delay for the Battleship.\n");
    printf("   - Part 2-B allows Escort ships to fire continuously with firing delays.\n\n");

    printf("3. Simulation Results\n");
    printf("   - Simulation results are saved in text files.\n");
    printf("   - Use Simulation Statistics to view previous results.\n\n");

    printf("4. Exit\n");
    printf("   - Select Exit from the Main Menu and confirm to close the simulator.\n");

    printf("\nEnter 1 to return to Main Menu: ");
    scanf("%d", &choice);
}

void ShowStatistics(){
    FILE *file;
    char line[300];
    int choice;

    printf("\n=== SIMULATION STATISTICS ===\n");

    printf("1. Initial Conditions\n");

    printf("\n--- PART 1 ---\n");
    printf("2. Part 1-A\n");
    printf("3. Part 1-B Simulation 1\n");
    printf("4. Part 1-B Simulation 2\n");
    printf("5. Part 1-C Simulation A\n");
    printf("6. Part 1-C Simulation B1\n");
    printf("7. Part 1-C Simulation B2\n");

    printf("\n--- PART 2-A ---\n");
    printf("8. Part 2-A Part 1-A\n");
    printf("9. Part 2-A Part 1-B Simulation 1\n");
    printf("10. Part 2-A Part 1-B Simulation 2\n");
    printf("11. Part 2-A Part 1-C A\n");
    printf("12. Part 2-A Part 1-C B1\n");
    printf("13. Part 2-A Part 1-C B2\n");

    printf("\n--- PART 2-B ---\n");
    printf("14. Part 2-B Part 1-A\n");
    printf("15. Part 2-B Part 1-B Simulation 1\n");
    printf("16. Part 2-B Part 1-B Simulation 2\n");
    printf("17. Part 2-B Part 1-C A\n");
    printf("18. Part 2-B Part 1-C B1\n");
    printf("19. Part 2-B Part 1-C B2\n");

    printf("\n20. Return to Main Menu\n");

    printf("Enter choice: ");
    scanf("%d", &choice);

    if (choice == 1){
        file = fopen("initial_conditions.txt", "r");
    }
    else if (choice == 2){
        file = fopen("part1a.txt", "r");
    }
    else if (choice == 3){
        file = fopen("part1b_simulation1.txt", "r");
    }
    else if (choice == 4){
        file = fopen("part1b_simulation2.txt", "r");
    }
    else if (choice == 5){
        file = fopen("part1c_simulationA.txt", "r");
    }
    else if (choice == 6){
        file = fopen("part1c_simulationB1.txt", "r");
    }
    else if (choice == 7){
        file = fopen("part1c_simulationB2.txt", "r");
    }
    else if (choice == 8){
        file = fopen("part2a_part1a.txt", "r");
    }
    else if (choice == 9){
        file = fopen("part2a_part1b_sim1.txt", "r");
    }
    else if (choice == 10){
        file = fopen("part2a_part1b_sim2.txt", "r");
    }
    else if (choice == 11){
        file = fopen("part2a_part1c_a.txt", "r");
    }
    else if (choice == 12){
        file = fopen("part2a_part1c_b1.txt", "r");
    }
    else if (choice == 13){
        file = fopen("part2a_part1c_b2.txt", "r");
    }
    else if (choice == 14){
        file = fopen("part2b_part1a.txt", "r");
    }
    else if (choice == 15){
        file = fopen("part2b_part1b_sim1.txt", "r");
    }
    else if (choice == 16){
        file = fopen("part2b_part1b_sim2.txt", "r");
    }
    else if (choice == 17){
        file = fopen("part2b_part1c_a.txt", "r");
    }
    else if (choice == 18){
        file = fopen("part2b_part1c_b1.txt", "r");
    }
    else if (choice == 19){
        file = fopen("part2b_part1c_b2.txt", "r");
    }
    else if (choice == 20){
        return;
    }
    else{
        printf("Invalid choice.\n");
        return;
    }

    if (file == NULL){
        printf("\nNo saved result found. Run the simulation first.\n");
        return;
    }

    printf("\n=== SAVED SIMULATION RESULT ===\n\n");

    while (fgets(line, sizeof(line), file) != NULL){
        printf("%s", line);
    }

    fclose(file);

    printf("\n");
}

void RunAllSimulations(){
    int d, n;

    int k;
    int pathX[100];
    int pathY[100];

    int t;
    float thetaMin;

    int initialBX;
    int initialBY;

    FILE *file;

    BattleShip B;

    printf("\n=== SIMULATION SETUP ===\n");

    printf("Enter battlefield size: ");
    scanf("%d", &d);

    printf("Enter the no of escort ships: ");
    scanf("%d", &n);

    printf("Enter Battleship type (U/M/R/S): ");
    scanf(" %c", &B.type);

    printf("Enter battleship X position: ");
    scanf("%d", &B.x);

    printf("Enter battleship Y position: ");
    scanf("%d", &B.y);

    printf("Enter battleship maximum shell velocity: ");
    scanf("%f", &B.maxVelocity);

    B.maxAttackRange = CalculateBattleshipMaxRange(B.maxVelocity);

    printf("\n--- Battleship Details ---\n");
    printf("Type = %c\n", B.type);
    printf("Position = (%d, %d)\n", B.x, B.y);
    printf("Maximum Shell Velocity = %.2f m/s\n", B.maxVelocity);
    printf("Battleship Maximum Attack Range = %.2f\n", B.maxAttackRange);

    initialBX = B.x;
    initialBY = B.y;
    EscortShip E[n];

    printf("\n--- Escortship Details ---\n");

    for (int i = 0; i < n; i++){
        E[i].index = i + 1;
        E[i].isAlive = 1;

        E[i].x = GenerateRandomCoordinate(d);
        E[i].y = GenerateRandomCoordinate(d);

        E[i].distanceFromB = CalculateDistance(B.x, B.y, E[i].x, E[i].y);

        E[i].type = GenerateRandomEscortType();
        E[i].angleRange = GetAngleRange(E[i].type);
        E[i].minAngle = GetMinimumAngle();
        E[i].maxAngle = E[i].minAngle + E[i].angleRange;
        E[i].bestAngle = GetBestAngle(E[i].minAngle, E[i].maxAngle);

        E[i].maxVelocity = GetMaximumVelocity(E[i].type, B.maxVelocity);
        E[i].minVelocity = GetMinimumVelocity(E[i].maxVelocity);

        E[i].impactPower = GetImpactPower(E[i].type);
        E[i].maxAttackRange = CalculateEscortMaxRange(E[i].maxVelocity, E[i].bestAngle);

        E[i].canBeHitByB = CanBattleshipHit(E[i].distanceFromB, B.maxAttackRange);
        E[i].canHitB = CanEscortHitBattleship(E[i].distanceFromB, E[i].maxAttackRange);


        if (E[i].canBeHitByB == 1){
            E[i].firingAngleFromB = CalculateFiringAngle(E[i].distanceFromB, B.maxVelocity);
            E[i].timeToHitFromB = CalculateTimeToHit(E[i].distanceFromB,B.maxVelocity, E[i].firingAngleFromB);
        }
        else{
            E[i].firingAngleFromB = 0;
            E[i].timeToHitFromB = 0;
        }
        printf("\nEscort Ship E%d\n", E[i].index);
        printf("Position = (%d, %d)\n", E[i].x, E[i].y);
        printf("Type = E%c\n", E[i].type);
        printf("Angle Range = %.1f\n", E[i].angleRange);
        printf("Min Angle = %.1f\n", E[i].minAngle);
        printf("Max Angle = %.1f\n", E[i].maxAngle);
        printf("Max Velocity = %.1f\n", E[i].maxVelocity);
        printf("Min Velocity = %.1f\n", E[i].minVelocity);
        printf("Impact Power = %.2f\n", E[i].impactPower);
        printf("Distance From B = %.2f\n", E[i].distanceFromB);
        printf("Best Angle = %.1f\n", E[i].bestAngle);
        printf("E Max Attack Range = %.2f\n", E[i].maxAttackRange);

        if (E[i].canBeHitByB == 1){
            printf("B Can Hit = YES\n");
        }
        else{
            printf("B Can Hit = NO\n");
        }

        if (E[i].canHitB == 1){
            printf("E Can Hit B = YES\n");
        }
        else{
            printf("E Can Hit B = NO\n");
        }
    }


    file = fopen("initial_conditions.txt", "w");

    if (file == NULL){
        printf("Error opening file!\n");
        return;
    }

    fprintf(file, "=== INITIAL BATTLEFIELD CONDITIONS ===\n\n");

    fprintf(file, "Battleship\n");
    fprintf(file, "Type = %c\n", B.type);
    fprintf(file, "Position = (%d, %d)\n", B.x, B.y);
    fprintf(file, "Max Velocity = %.2f\n", B.maxVelocity);
    fprintf(file, "Max Attack Range = %.2f\n\n", B.maxAttackRange);

    fprintf(file, "Escort Ships\n\n");

    for (int i = 0; i < n; i++){
        fprintf(file, "Escort Ship E%d\n", E[i].index);
        fprintf(file, "Position = (%d, %d)\n", E[i].x, E[i].y);
        fprintf(file, "Type = E%c\n", E[i].type);
        fprintf(file, "Angle Range = %.1f\n", E[i].angleRange);
        fprintf(file, "Min Angle = %.1f\n", E[i].minAngle);
        fprintf(file, "Max Angle = %.1f\n", E[i].maxAngle);
        fprintf(file, "Min Velocity = %.1f\n", E[i].minVelocity);
        fprintf(file, "Max Velocity = %.1f\n", E[i].maxVelocity);
        fprintf(file, "Impact Power = %.2f\n\n", E[i].impactPower);
    }

    fclose(file);

    // PART 1
    RunPart1A(B, E, n);

    printf("\nEnter number of path points: ");
    scanf("%d", &k);

    if (k < 1 || k > 100){
        printf("Number of path points must be between 1 and 100.\n");
        return;
    }

    RunPart1BSimulation1(B, E, n, k, pathX, pathY, d);

    printf("\n=== Part 1-B Simulation 2 ===\n");

    printf("Enter the iteration after which the gun jams: ");
    scanf("%d", &t);

    if (t < 1 || t >= k){
        printf("Jam iteration must be between 1 and %d.\n", k - 1);
        return;
    }

    printf("Enter minimum firing angle after jam: ");
    scanf("%f", &thetaMin);

    if (thetaMin <= 0 || thetaMin >= 30){
        printf("Minimum firing angle must be between 0 and 30 degrees.\n");
        return;
    }

    RunPart1BSimulation2(B, E, n, k, pathX, pathY, t, thetaMin);

    RunPart1CSimulationA(B, E, n, initialBX, initialBY);

    RunPart1CSimulationB1(B, E, n, k, pathX, pathY);

    RunPart1CSimulationB2(B, E, n, k, pathX, pathY, t, thetaMin);

    // PART 2-A
    float TBq;

    printf("\nEnter B firing delay TBq: ");
    scanf("%f", &TBq);

    RunPart2APart1A(B, E, n, TBq);

    RunPart2APart1BSim1(B, E, n, k, pathX, pathY, d, TBq);

    RunPart2APart1BSim2(B, E, n, k, pathX, pathY, t, thetaMin, TBq);

    RunPart2APart1CA(B, E, n, TBq);

    RunPart2APart1CB1(B, E, n, k, pathX, pathY, TBq);

    RunPart2APart1CB2(B, E, n, k, pathX, pathY, t, thetaMin, TBq);

    // PART 2-B
    float TEA, TEB, TEC, TED, TEE;

    printf("\n=== PART 2-B FIRING DELAYS ===\n");

    printf("Enter firing delay for EA: ");
    scanf("%f", &TEA);

    printf("Enter firing delay for EB: ");
    scanf("%f", &TEB);

    printf("Enter firing delay for EC: ");
    scanf("%f", &TEC);

    printf("Enter firing delay for ED: ");
    scanf("%f", &TED);

    printf("Enter firing delay for EE: ");
    scanf("%f", &TEE);


    RunPart2BPart1A(B, E, n, TBq, TEA, TEB, TEC, TED, TEE);

    RunPart2BPart1BSim1(B, E, n, k, pathX, pathY, TBq, TEA, TEB, TEC, TED, TEE);

    RunPart2BPart1BSim2(B, E, n, k, pathX, pathY, t, thetaMin, TBq,TEA, TEB, TEC, TED, TEE);

    RunPart2BPart1CA(B, E, n, TBq, TEA, TEB, TEC, TED, TEE);

    RunPart2BPart1CB1(B, E, n, k, pathX, pathY, TBq, TEA, TEB, TEC, TED, TEE);

    RunPart2BPart1CB2(B, E, n, k, pathX, pathY,t, thetaMin, TBq, TEA, TEB, TEC, TED, TEE);

    printf("\n=== ALL SIMULATIONS COMPLETED ===\n");
}


int main(){
    int choice;
    int exitChoice;
    unsigned int seed;

    seed = time(NULL);
    srand(seed);

    while (1){
        printf("\n");
printf("\n");
printf("                                         A D V A N C E D   N A V A L   B A T T L E\n");
printf("                                                   S I M U L A T O R\n");
printf("=====================================================================================================================\n\n");
        printf("1. Start Simulation\n");
        printf("2. View Instructions\n");
        printf("3. Simulation Statistics\n");
        printf("4. Set Random Seed\n");
        printf("5. Exit\n");

        printf("Enter choice: ");
        scanf("%d", &choice);

        if (choice == 1){
            RunAllSimulations();
        }

        else if (choice == 2){
            ShowInstructions();
        }

        else if (choice == 3){
            ShowStatistics();
        }
        else if (choice == 4){
            printf("\nEnter random seed value: ");
            scanf("%u", &seed);

            srand(seed);

            printf("Random seed set to %u\n", seed);
        }

        else if (choice == 5){
            printf("\nAre you sure you want to exit?\n");
            printf("1. Yes\n");
            printf("2. No\n");
            printf("Enter choice: ");
            scanf("%d", &exitChoice);

            if (exitChoice == 1){
                printf("Closing simulator...\n");
                break;
            }
        }
        else{
            printf("Invalid choice. Please try again.\n");
        }
    }
    return 0;
}
